Try to find npm/node binaries in older meteors

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -130,10 +130,36 @@ if [ -z "$SERVER_ONLY_FLAG" ]; then
   echo "-----> Moving on."
 fi
 
+# Identify the npm/node to use.  For Meteors > 1.3, we use `meteor npm` and
+# `meteor node` to find the bundled binaries.  For older releases, we need to
+# resort to using `find` to search out the appropriate version within the
+# bundle.
+set +e
+HOME=$METEOR_DIR $METEOR npm --version
+METEOR_NPM_EXIT_CODE=$?
+set -e
+if [ $METEOR_NPM_EXIT_CODE -eq 0 ]; then
+  # Newer meteor: it knows how to find its own npm/node.
+  METEOR_NPM="$METEOR npm"
+else
+  # Older meteor: search out npm/node within $METEOR_DIR.
+  BARE_VERSION=`cat $APP_RELEASE | sed -e 's/METEOR@//'`
+  METEOR_NPM=`find $METEOR_DIR -wholename "*$BARE_VERSION*/dev_bundle/bin/npm"`
+  METEOR_NODE=`find $METEOR_DIR -wholename "*$BARE_VERSION*/dev_bundle/bin/node"`
+  if [ -z "$METEOR_NPM" || -z "$METEOR_NODE" ] ; then
+    echo "FATAL: Can't find npm/node within meteor bundle. This is a bug. Please open an issue at https://github.com/AdmitHub/meteor-buildpack-horse.";
+    exit 1
+  fi
+  # Create link to node for use by bin/release, so it doesn't have to do a
+  # messy `find` with the release version. Use a hard link so that we can move
+  # $METEOR_DIR around without the link breaking.
+  ln $METEOR_NODE $METEOR_DIR/meteor-node
+fi
+
 # If we use npm on root, run npm install.  Don't use `--production` here, as we
 # may need devDependencies (e.g. webpack) in order to build the meteor app.
 if [ -e "$APP_SOURCE_DIR"/package.json ]; then
-  HOME=$METEOR_DIR $METEOR npm install
+  HOME=$METEOR_DIR $METEOR_NPM install
 fi
 
 # Related to https://github.com/meteor/meteor/issues/2796 and 
@@ -159,7 +185,7 @@ rmdir $BUNDLE_DEST
 # Run npm install on the built slug; only for `--production` dependencies.
 if [ -e "$COMPILE_DIR"/app/programs/server/package.json ]; then
   cd "$COMPILE_DIR"/app/programs/server
-  HOME=$METEOR_DIR $METEOR npm install --production
+  HOME=$METEOR_DIR $METEOR_NPM install --production
 fi
 
 # Move meteor installation to where we can use it in bin/release
